name: Main workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest ]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: egor-tensin/vs-shell@v2
      if: ${{ runner.os == 'Windows' }}
    - run: rustup default nightly
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose --release
    - name: Strip
      if: ${{ runner.os != 'Windows' }}
      run: strip ${{ github.workspace }}/target/release/sdftool
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: SDFTool for ${{ runner.os }}
        path: |
          ${{ github.workspace }}/target/release/sdftool
          ${{ github.workspace }}/target/release/sdftool.exe

          
        
